# Docker Compose configuration for Finance Monkey

services:
  postgres:
    image: postgres:14
    container_name: finance-monkey-postgres
    environment:
      POSTGRES_DB: finance_monkey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: finance-monkey-backend
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/finance_monkey
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=developmentSecretKeyWithMoreThan256BitsToSatisfyJWTRequirements
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:8080/api/auth/oauth2/callback/google}
      - SERVER_SERVLET_CONTEXT_PATH=/api
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
