spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000 # 1 hour in milliseconds

email:
  processing:
    schedule: "0 */30 * * * *" # Every 30 minutes
    batch-size: 50
    max-retries: 3

gemini:
  api:
    key: ${GEMINI_API_KEY}
  project: ${GEMINI_PROJECT:finance-monkey}
  location: ${GEMINI_LOCATION:us-central1}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      
logging:
  level:
    org.springframework.security: WARN
    com.financeMonkey: INFO
  file:
    name: /var/log/finance-monkey.log
