spring:
  # Connection settings for resiliency
  datasource:
    # These settings help with connection issues in cloud environments
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      # Don't fail initialization forever
      initialization-fail-timeout: -1
      # Add a large connection timeout for DNS resolution issues
      connection-timeout: 30000
      # Continue trying to acquire connection
      keepalive-time: 60000
      # Only validate once every 10 seconds to reduce load
      validation-timeout: 10000
      # Retry connection validation 
      max-lifetime: 180000
    
    # Enable connection retry for database connectivity issues
    tomcat:
      max-wait: 20000
      test-on-borrow: true
      
  # Configuration for managing DNS resolution issues in cloud environments
  cloud:
    # Render-specific settings
    render:
      # Allow more time for DNS resolution
      connection-timeout: 30000
  
  # Make application more tolerant to failures
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        # Set to true to show generated SQL
        show_sql: false
        # Configure connection retry
        connection.provider_disables_autocommit: false
        # Defer data source initialization
        connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
    show-sql: false
    # Don't fail on startup if database is not available
    open-in-view: false
    
  # Make Flyway also more resilient
  flyway:
    enabled: true
    baseline-on-migrate: true
    # Add connection retry
    connect-retries: 10
    connect-retries-interval: 5s
    # Don't fail on startup if migration fails
    fail-on-missing-locations: false
    # Don't validate on migrate to avoid connection issues
    validate-on-migrate: false

server:
  port: ${PORT:10000}
  servlet:
    context-path: /api

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000 # 1 hour in milliseconds

email:
  processing:
    schedule: "0 */30 * * * *" # Every 30 minutes
    batch-size: 50
    max-retries: 3

gemini:
  api:
    key: ${GEMINI_API_KEY}
  project: ${GEMINI_PROJECT:finance-monkey}
  location: ${GEMINI_LOCATION:us-central1}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      
logging:
  level:
    org.springframework.security: WARN
    com.financeMonkey: INFO
  file:
    name: /var/log/finance-monkey.log
