spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_monkey
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:verySecretKeyThatShouldBeChangedInProduction}
      expire-length: 3600000 # 1 hour in milliseconds

email:
  processing:
    schedule: "0 */30 * * * *" # Every 30 minutes
    batch-size: 50
    max-retries: 3

gemini:
  api:
    key: ${GEMINI_API_KEY:your-gemini-api-key}
  project: ${GEMINI_PROJECT:finance-monkey}
  location: ${GEMINI_LOCATION:us-central1}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
    client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/oauth2/callback/google}
  application:
    name: ${GOOGLE_APP_NAME:Finance Monkey}
  drive:
    # The same OAuth credentials will be used for both Gmail and Drive access
    # Make sure the Drive API is enabled in your Google Cloud project
    export:
      schedule: "0 0 1 1 * ?" # Monthly at 1am on the 1st day

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    org.springframework.security: INFO
    com.financeMonkey: DEBUG
