# Docker-specific Spring Boot configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-threads: 200

# Logging
logging:
  level:
    root: INFO
    com.financeMonkey: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

# Security
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # 24 hours in milliseconds

# Google API Configuration
google:
  application:
    name: Finance Monkey
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}
  api:
    gemini: ${GEMINI_API_KEY}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
